# Change these first
owner: erikd256 # Your GitHub organization or username, where this repository lives
repo: status.stfranciscus-heverlee.org # The name of this repository
sites:
  - name: Homepage
    url: https://stfranciscus-heverlee.org
  - name: CDN
    check: "tcp-ping"
    url: assets.tina.io
    port: 443
  - name: API
    check: "tcp-ping"
    url: $API_URL
    port: 443
  - name: Analytics
    url: $ANALYTICS_URL
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stfranciscus-heverlee.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status @ St.-Franciscusparochie Heverlee
  introTitle: "Status @ Sint-Franciscusparochie Heverlee"
  introMessage: Hier kan je terugvinden of een van onze services offline is of dat misschien toch jouw internetverbinding hapert.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
i18n:
  history: "Geschiedenis"
  responseTime: "Response Time"
  uptime: "Uptime"
  up: "🟩 Online"
  degraded: "🟨 Trage reactie"
  down: "🟥 Offline"
  allSystemsOperational: "🟩 Alle systemen online en functioneel."
  degradedPerformance: "🟨 Oepsie, een van onze systemen reageert traag, eventueel ervaar je problemen bij het gebruiken van onze website."
  completeOutage: "🟥 Oepsie, al onze systemen zijn offline, eventueel ervaar je problemen bij het gebruiken van onze website."
  partialOutage: "🟧 Oepsie, een van onze systemen is offline, eventueel ervaar je problemen bij het gebruiken van onze website."
  activeIncidents: "Actieve Incidenten"
commitMessages:
  commitAuthorName: "Erik D."
  commitAuthorEmail: "62072464+erikd256@users.noreply.github.com"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
