# Change these first
owner: erikd256 # Your GitHub organization or username, where this repository lives
repo: status.stfranciscus-heverlee.org # The name of this repository
sites:
  - name: Homepage
    url: https://stfranciscus-heverlee.org
  - name: CDN
    check: "tcp-ping"
    url: assets.tina.io
    port: 443
  - name: API
    check: "tcp-ping"
    url: $API_URL
    port: 443
  - name: Analytics
    url: $ANALYTICS_URL
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stfranciscus-heverlee.org
  themeUrl: https://raw.githubusercontent.com/erikd256/status.stfranciscus-heverlee.org/master/assets/custom.css
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status @ St.-Franciscusparochie Heverlee
  introTitle: "Status @ Sint-Franciscusparochie Heverlee"
  introMessage: Hier kan je terugvinden of een van onze services offline is of dat misschien toch jouw internetverbinding hapert.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
i18n:
  activeIncidents: Actieve Incidenten
  allSystemsOperational: Alle systemen operationeel
  incidentReport: "Incident #$NUMBER rapport →"
  activeIncidentSummary: Geopend op $DATE met $POSTS-berichten
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Opgelost
  incidentOngoing: Voortdurend
  incidentOpenedAt: Geopend op
  incidentClosedAt: Opgelost op
  incidentViewOnGitHub: Bekijk en abonneer op GitHub
  incidentCommentSummary: Gecommenteerd op $DATE door $AUTHOR
  incidentBack: ← Terug naar alle incidenten
  pastIncidents: Verleden incidenten
  pastIncidentsResolved: Opgelost in $MINUTES minuten met $POSTS posts
  liveStatus: Live-status
  overallUptime: "Gemmidelde beschikbaarheid: $UPTIME"
  overallUptimeTitle: Gemiddelde beschikbaarheid
  averageResponseTime: "Gemiddelde reactietijd: $TIMEms"
  averageResponseTimeTitle: Gemiddelde reactietijd
  sevelDayResponseTime: 7-dagen gemiddelde reactietijd
  responseTimeMs: Reactietijd (ms)
  up: Online
  down: Offline
  degraded: Verslechterd
  ms: ms
  loading: Laden
  navGitHub: GitHub
  footer:  Deze pagina is [open source]($REPO), mogelijk gemaakt door [Upptime](https://upptime.js.org)
  errorTitle: Een fout is opgetreden
  errorIntro: Er is een fout opgetreden bij het laden van de laatste statusdetails.
  errorText: Probeer het binnen enkele ogenblikken opnieuw.
  errorHome: Ga naar de homepage
  pastScheduledMaintenance: Eerder gepland onderhoud
  scheduledMaintenance: Gepland onderhoud
  scheduledMaintenanceSummaryStarted: Gestart om $DATE voor $DURATION minuten
  scheduledMaintenanceSummaryStarts: Begint om $DATE voor $DURATION minuten
  startedAt: Gestart om
  startsAt: Start om
  duration: Duur
  durationMin: $DURATION minuten
  incidentCompleted: Voltooid
  incidentScheduled: Gepland
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1j
  durationAll: tot.
commitMessages:
  commitAuthorName: "Erik D."
  commitAuthorEmail: "62072464+erikd256@users.noreply.github.com"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
